In [2]:
from splinter import Browser 
import pandas as pd
from bs4 import BeautifulSoup
from time import sleep
from tqdm import tqdm_notebook

In [3]:
browser = Browser('chrome')

In [4]:
browser.visit('https://www.whiskystats.net/whisky-database/#')

In [9]:
soup = BeautifulSoup(browser.html, 'html.parser')

In [ ]:
soup.find_all('th')[3].text

In [10]:
def load_page():
    num_times = int(int(soup.find('div', {'id':'result-nof'}).text.split()[0])/100)
    btn = browser.find_by_text('Load More').first
    i = num_times
    while i > 0:
        print(num_times - i)
        try:
            btn.click()
        except Exception as e:
            print(e)
            sleep(2)
#             i += 1
        sleep(.2)
        i -= 1

In [70]:
def load_page_2():
    num_times = int(int(soup.find('div', {'id':'result-nof'}).text.split()[0])/100)
    btn = browser.find_by_text('Load More').first
    for i in tqdm_notebook(range(num_times)):
        btn.click()
        sleep(5)

In [71]:
load_page_2()

HBox(children=(IntProgress(value=0, max=375), HTML(value='')))

StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=75.0.3770.142)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.17134 x86_64)

In [13]:
soup.find('div', {'id':'result-nof'})

In [12]:
soup = BeautifulSoup(browser.html, 'html.parser')

In [13]:
len(soup.find_all('th'))

3707

In [14]:
ths = soup.find_all('th')

In [17]:
df = pd.DataFrame(columns = ['bottle'], index = [i for i in range(38000)])

In [56]:
for i in range(len(ths)):
    df.iat[i, 0] = ths[i].text

In [57]:
df.drop(0).head()

,bottle,age,abv,ml,price
1,"Burberry, A. Gillies & Co",12,13 €March 2016,12,43.00%
2,"Burberry, A. Gillies & Co",32 €April 2019,1000,32 €April 2019,10
3,"Burberry, A. Gillies & Co",750,43.00%,750,78 €December 2017
4,"Burberry, A. Gillies & CoReplica Bottling",43.00%,1968,43.00%,750
5,"Burberry, A. Gillies & Co Decanter",25,497 €July 2017,25,40.00%

In [48]:
tds = soup.find_all('td', class_ = 'st-val')

In [49]:
df['age'] = ''
df['abv'] = ''
df['ml'] = ''
df['price'] = ''

In [68]:
cnt = -1
for i in tqdm_notebook(range(len(df))):
    try:
        if (i % 4) == 0:
            cnt += 1
        df.iat[cnt, (i%4)+1] = tds[i].text
    except:
        print(cnt)
        break
    
#     print(i)

HBox(children=(IntProgress(value=0, max=38000), HTML(value='')))

3961

In [69]:
df

,bottle,age,abv,ml,price
0,Results,5,40.00%,700,13 €March 2016
1,"Burberry, A. Gillies & Co",12,43.00%,1000,32 €April 2019
2,"Burberry, A. Gillies & Co",10,43.00%,750,78 €December 2017
3,"Burberry, A. Gillies & Co",1968,43.00%,750,497 €July 2017
4,"Burberry, A. Gillies & CoReplica Bottling",25,40.00%,700,79 €May 2019
5,"Burberry, A. Gillies & Co Decanter",15,43.00%,750,77 €April 2019
6,"Burberry, A. Gillies & Co",5,40.00%,700,11 €March 2019
7,"Burberry, A. Gillies & CoPremium",15,40.00%,700,22 €June 2019
8,"Burberry, A. Gillies & Co",23,40.00%,700,107 €June 2018
9,"Burberry, A. Gillies & CoMaster Blenders Speci...",12,40.00%,750,38 €October 2015
10,"Burberry, A. Gillies & Co",12,43.00%,750,17 €January 2019
11,"Burberry, A. Gillies & Co",12,43.00%,750,62 €July 2017
12,"Burberry, A. Gillies & Co (1980s)",15,43.00%,750,68 €December 2017
13,"Burberry, A. Gillies & Co (1980s)",12,40.00%,700,44 €November 2018
14,"Burberry, A. Gillies & Co (1980s)",25,43.00%,750,187 €November 2018
15,"Burberry, A. Gillies & Co (Crystal Decanter) D...",15,40.00%,700,19 €March 2019
16,"Burberry, A. Gillies & Co (Old Style)",18,48.60%,700,115 €April 2019
17,"The Glover, AdelphiFirst Edition",15,1991,60.20%,700
18,"Breath of Speyside, Adelphi b.2006One of 615 B...",165 €August 2018,14,1993,57.70%
19,"Breath of Islay, Adelphi b.2007One of 265 Bott...",700,103 €December 2015,13,1999
20,"Breath of Islay, Adelphi b.2012One of 291 Bott...",56.60%,700,100 €March 2019,12
21,"Laudale, AdelphiOne of 3458 Bottles",46.00%,700,180 €May 2019,11
22,"Breath of Islay, Adelphi b.2010One of 266 Bott...",1999,56.60%,700,92 €May 2015
23,"Breath of Islay, Adelphi b.2006One of 278 Bott...",14,1992,56.50%,700
24,"Breath of Speyside, Adelphi b.2009One of 612 B...",82 €December 2018,18,1991,54.30%
25,"Breath of Islay, Adelphi b.2008One of 279 Bott...",700,233 €March 2016,16,1992
26,"The Glover, Adelphi",56.40%,700,70 €February 2012,14
27,"Breath of Speyside, Adelphi b.2009One of 520 B...",44.30%,700,108 €April 2019,18
28,"The Glover, AdelphiOne of 390 Bottles",1991,54.20%,700,258 €March 2016
29,"Breath of Islay, Adelphi b.2005One of 266 Bott...",22,60.00%,700,833 €March 2019
...,...,...,...,...,...
37970,NaN,,,,
37971,NaN,,,,
37972,NaN,,,,
37973,NaN,,,,
37974,NaN,,,,
37975,NaN,,,,
37976,NaN,,,,
37977,NaN,,,,
37978,NaN,,,,
37979,NaN,,,,
37980,NaN,,,,
37981,NaN,,,,
37982,NaN,,,,
37983,NaN,,,,
37984,NaN,,,,
37985,NaN,,,,
37986,NaN,,,,
37987,NaN,,,,
37988,NaN,,,,
37989,NaN,,,,
37990,NaN,,,,
37991,NaN,,,,
37992,NaN,,,,
37993,NaN,,,,
37994,NaN,,,,
37995,NaN,,,,
37996,NaN,,,,
37997,NaN,,,,
37998,NaN,,,,
37999,NaN,,,,

In [63]:
for i in range(10):
    print(tds[i].text)

5
40.00%
700
13 €March 2016
12
43.00%
1000
32 €April 2019
10
43.00%

In [62]:
tds[0].text

'5'